site_name: qbt-flow-utils
repo_url: https://github.com/LimeDrive/qbt-flow-utils
site_url: https://LimeDrive.github.io/qbt-flow-utils
site_description: This project offers automated torrent flow management through auto-tagging, disk space optimization, torrent and cross-seed management, media folder hygiene, tracker automation, and more to come.
site_author: LimeCat on Hub's
edit_uri: edit/main/docs/
repo_name: LimeDrive/qbt-flow-utils
copyright: Maintained by <a href="https://LimeDrive.com">LimeCat</a>.

nav:
- Home: index.md
- Configuration:
  - Tracker Configuration: config/trackers.md
plugins:
- search
- mkdocstrings:
    handlers:
      python:
        setup_commands:
        - import sys
        - sys.path.append('../')
theme:
  name: material
  feature:
    tabs: true
  palette:
  - media: "(prefers-color-scheme: light)"
    scheme: default
    primary: white
    accent: deep orange
    toggle:
      icon: material/brightness-7
      name: Switch to dark mode
  - media: "(prefers-color-scheme: dark)"
    scheme: slate
    primary: black
    accent: deep orange
    toggle:
      icon: material/brightness-4
      name: Switch to light mode
  icon:
    repo: fontawesome/brands/github

extra:
  social:
  - icon: fontawesome/brands/github
    link: https://github.com/LimeDrive/qbt-flow-utils
  - icon: fontawesome/brands/python
    link: https://pypi.org/project/qbt-flow-utils

markdown_extensions:
- toc:
    permalink: true
- pymdownx.arithmatex:
    generic: true
